// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioController from "./audio_controller"
application.register("audio", AudioController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MiQuizController from "./mi_quiz_controller"
application.register("mi-quiz", MiQuizController)

import StagesOfChangeListController from "./stages_of_change_list_controller"
application.register("stages-of-change-list", StagesOfChangeListController)
